services:
  opensearch-node1:
    image: opensearchproject/opensearch:${OPENSEARCH_TAG:-latest}
    container_name: opensearch-node1
    environment:
      - cluster.name=${CLUSTER_NAME:-opensearch-cluster}
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS:--Xms512m -Xmx512m}"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "${OPENSEARCH_HTTP_PORT:-9200}:9200"
      - "${OPENSEARCH_DIAG_PORT:-9600}:9600"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [opensearch-net]

  opensearch-node2:
    image: opensearchproject/opensearch:${OPENSEARCH_TAG:-latest}
    container_name: opensearch-node2
    environment:
      - cluster.name=${CLUSTER_NAME:-opensearch-cluster}
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS:--Xms512m -Xmx512m}"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks: [opensearch-net]

  dashboards:
    image: opensearchproject/opensearch-dashboards:${DASHBOARDS_TAG:-latest}
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200","http://opensearch-node2:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    ports:
      - "${DASHBOARDS_PORT:-5601}:5601"
    depends_on:
      - opensearch-node1
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5601/api/status"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [opensearch-net]

networks:
  opensearch-net:

volumes:
  opensearch-data1:
  opensearch-data2:
